### ISSUE TITLE
Wrong hash for the original map file

### ISSUE THREAD

**Issue by kapistelijaJami** [NoxPhoenix/custom-map-loader#1]
I was getting the error 'Could not find valid underpass map file.!' as probably many others. It is because manageMapFiles.js originalMapHashes array doesnt include the correct hash. I added this hash into the array and now it works as expected: '1202a06278bb9a4b39e48e8b1cd7bdce'

**Comment by NoxPhoenix** [comment]
This is correct. For some reason, Psyonix makes tiny changes in every little update to the underpass map file and it needs a new hash. I am updating this behavior to have a more safe way of storing the map file so the user can't overwrite it and then I can abandon the hash comparisons all together.
