### ISSUE TITLE
Every time I click download as zip, it says this site can't be reached

### ISSUE THREAD

**Issue by DogeLord081** [NoxPhoenix/custom-map-loader#2]

**Comment by NoxPhoenix** [comment]
Can you provide more info?

**Comment by DogeLord081** [comment]
> Can you provide more info?

Sure, so first, when I try to load a map it says something about the underpass map not loading and so that's why I tried to download the source code to fix it but then, when I click download code as a zip it doesn't download and it leads me to This site can't be reached

**Comment by DogeLord081** [comment]
@NoxPhoenix i got a new pc and its working now :D
